// Node.js test runner — no vitest/esbuild needed
import { cube, sphere, cylinder, translate, rotate, union, variable, echo, importFile, color, polygon, forLoop, ifNode, moduleDef } from '../dist/src/lib/scad-ast.js';
import { emit, emitDocument } from '../dist/src/lib/scad-emitter.js';
import { createServer } from '../dist/src/server.js';
import { registerAllTools } from '../dist/src/tools/index.js';

let passed = 0, failed = 0;
function test(name, fn) {
  try { fn(); passed++; console.log(`  ✅ ${name}`); }
  catch(e) { failed++; console.log(`  ❌ ${name}: ${e.message}`); }
}

console.log('\n=== SCAD AST Tests ===');
test('cube', () => { const n = cube([10,20,30], true); if (n.type !== 'cube') throw new Error(); });
test('sphere', () => { const n = sphere(10, {$fn: 100}); if (n.r !== 10 || n.$fn !== 100) throw new Error(); });
test('cylinder', () => { const n = cylinder({h: 20, r: 10}); if (n.h !== 20) throw new Error(); });
test('translate', () => { const n = translate([1,2,3], [cube(10)]); if (n.v[0] !== 1) throw new Error(); });
test('rotate', () => { const n = rotate({a: 45, v: [0,0,1], children: [cube(5)]}); if (n.a !== 45) throw new Error(); });
test('union', () => { const n = union([cube(10), sphere(5)]); if (n.children.length !== 2) throw new Error(); });
test('variable', () => { const n = variable('w', 50); if (n.value !== 50) throw new Error(); });
test('echo', () => { const n = echo('hi'); if (n.message !== 'hi') throw new Error(); });
test('importFile', () => { const n = importFile('x.stl'); if (n.file !== 'x.stl') throw new Error(); });
test('color', () => { const n = color('red', [cube(10)]); if (n.c !== 'red') throw new Error(); });
test('polygon', () => { const n = polygon([[0,0],[10,0],[5,10]]); if (n.points.length !== 3) throw new Error(); });

console.log('\n=== SCAD Emitter Tests ===');
test('emit cube', () => { if (!emit(cube([10,20,30])).includes('cube')) throw new Error(); });
test('emit sphere $fn', () => { if (!emit(sphere(10, {$fn: 100})).includes('$fn = 100')) throw new Error(); });
test('emit translate', () => { if (!emit(translate([1,2,3], [cube(5)])).includes('translate')) throw new Error(); });
test('emit union braces', () => { if (!emit(union([cube(10), sphere(5)])).includes('{')) throw new Error(); });
test('emit variable', () => { if (emit(variable('w', 50)) !== 'w = 50;') throw new Error(); });
test('emit echo', () => { if (emit(echo('x')) !== 'echo("x");') throw new Error(); });
test('emit import', () => { if (!emit(importFile('a.stl')).includes('a.stl')) throw new Error(); });
test('emit color', () => { if (!emit(color('red', [cube(10)])).includes('"red"')) throw new Error(); });
test('emit doc header', () => { if (!emitDocument([cube(10)]).includes('Generated by')) throw new Error(); });
test('emit for range', () => { if (!emit(forLoop('i', {start:0, end:10, step:2}, [cube(5)])).includes('[0:2:10]')) throw new Error(); });
test('emit if', () => { if (!emit(ifNode('x>5', [cube(5)], [sphere(3)])).includes('else')) throw new Error(); });
test('emit module', () => { if (!emit(moduleDef('box', [{name:'s', default:10}], [cube(20)])).includes('module box')) throw new Error(); });

console.log('\n=== Tool Tests ===');
test('server creates', () => { if (!createServer({name:'t', version:'1'})) throw new Error(); });
test('single consolidated tool registered', () => {
  const s = createServer({name:'t', version:'1'}); registerAllTools(s);
  const names = Object.keys(s._tools);
  if (names.length !== 1 || !s._tools['design_3d_model']) throw new Error(names.join(','));
});
test('design_3d_model emits a single-node AST', async () => {
  const s = createServer({name:'t', version:'1'}); registerAllTools(s);
  const r = await s.callTool('design_3d_model', {ast: {type:'cube', size:[10,20,30]}});
  if (!JSON.parse(r.content[0].text).scad_code.includes('cube')) throw new Error();
});
test('design_3d_model emits nested booleans', async () => {
  const s = createServer({name:'t', version:'1'}); registerAllTools(s);
  const r = await s.callTool('design_3d_model', {ast: {type:'difference', children:[
    {type:'cube', size:[20,20,10], center:true},
    {type:'cylinder', h:12, r:4, center:true},
  ]}});
  const code = JSON.parse(r.content[0].text).scad_code;
  if (!code.includes('difference') || !code.includes('cylinder')) throw new Error();
});
test('design_3d_model treats array as implicit union', async () => {
  const s = createServer({name:'t', version:'1'}); registerAllTools(s);
  const r = await s.callTool('design_3d_model', {ast: [{type:'cube', size:10}, {type:'sphere', r:5}]});
  const parsed = JSON.parse(r.content[0].text);
  if (parsed.ast.type !== 'union' || parsed.ast.children.length !== 2) throw new Error();
});
test('design_3d_model rejects missing ast', async () => {
  const s = createServer({name:'t', version:'1'}); registerAllTools(s);
  let threw = false;
  try { await s.callTool('design_3d_model', {}); } catch { threw = true; }
  if (!threw) throw new Error('expected throw');
});

console.log(`\n=== ${passed} passed, ${failed} failed ===\n`);
process.exit(failed > 0 ? 1 : 0);
