import { describe, it, expect } from "vitest";
import { emit, emitDocument } from "../src/lib/scad-emitter.js";
import { cube, sphere, translate, rotate, union, difference, linearExtrude, variable, moduleDef, echo, importFile, color, forLoop } from "../src/lib/scad-ast.js";

describe("SCAD Emitter", () => {
  it("emits a cube", () => {
    const code = emit(cube([10, 20, 30]));
    expect(code).toContain("cube");
    expect(code).toContain("10");
    expect(code).toContain("20");
    expect(code).toContain("30");
  });

  it("emits a sphere with $fn", () => {
    const code = emit(sphere(10, { $fn: 100 }));
    expect(code).toContain("sphere");
    expect(code).toContain("$fn = 100");
  });

  it("emits a translate with children", () => {
    const node = translate([1, 2, 3], [cube(10)]);
    const code = emit(node);
    expect(code).toContain("translate");
    expect(code).toContain("1");
    expect(code).toContain("2");
    expect(code).toContain("3");
    expect(code).toContain("cube");
  });

  it("emits a union", () => {
    const node = union([cube(10), sphere(5)]);
    const code = emit(node);
    expect(code).toContain("union");
    expect(code).toContain("{");
    expect(code).toContain("}");
  });

  it("emits a document with header", () => {
    const doc = emitDocument([cube(10), sphere(5)]);
    expect(doc).toContain("// Generated by OpenSCAD MCP Server");
    expect(doc).toContain("cube");
    expect(doc).toContain("sphere");
  });

  it("emits a variable assignment", () => {
    const code = emit(variable("width", 50));
    expect(code).toContain("width = 50");
  });

  it("emits a linear_extrude", () => {
    const node = linearExtrude({ height: 30, twist: 45, children: [cube([20, 20, 1])] });
    const code = emit(node);
    expect(code).toContain("linear_extrude");
    expect(code).toContain("height = 30");
    expect(code).toContain("twist = 45");
  });

  it("emits echo", () => {
    const code = emit(echo("debug message"));
    expect(code).toBe('echo("debug message");');
  });

  it("emits import", () => {
    const code = emit(importFile("model.stl", 10));
    expect(code).toContain('import(file = "model.stl"');
    expect(code).toContain("convexity = 10");
  });

  it("emits color with string", () => {
    const code = emit(color("red", [cube(10)]));
    expect(code).toContain('color(c = "red")');
    expect(code).toContain("cube");
  });

  it("emits for loop", () => {
    const code = emit(forLoop("i", [1, 2, 3], [cube(5)]));
    expect(code).toContain("for (i = [1, 2, 3])");
    expect(code).toContain("{");
    expect(code).toContain("cube");
  });

  it("emits for loop with range object", () => {
    const code = emit(forLoop("i", { start: 0, end: 10, step: 2 }, [cube(5)]));
    expect(code).toContain("for (i = [0:2:10])");
  });
});
