// Reads the Vite single-file UI bundle and emits it as a TypeScript module
// exporting the HTML as a string. The Vercel serverless function imports that
// module instead of reading from disk — the function bundle can't rely on
// arbitrary build artifacts being present at runtime.

import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const htmlPath = resolve(repoRoot, "ui/dist/mcp-app.html");
const outPath = resolve(repoRoot, "src/generated/app-html.ts");

let html;
try {
  html = await readFile(htmlPath, "utf-8");
} catch {
  console.error(
    `inline-html: ${htmlPath} not found — run \`npm run build:ui\` first.`,
  );
  process.exit(1);
}

await mkdir(dirname(outPath), { recursive: true });
await writeFile(
  outPath,
  "// AUTO-GENERATED by scripts/inline-html.mjs — do not edit by hand.\n" +
    "// Source: ui/dist/mcp-app.html (Vite single-file bundle)\n" +
    `export const APP_HTML = ${JSON.stringify(html)};\n`,
);

console.log(
  `inline-html: ${(html.length / 1024).toFixed(1)} KB -> src/generated/app-html.ts`,
);
